<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/Conjugated_Transpose_20240320.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
######################################################
# 코드의 목적: Quantum Computer접속 및 Job 제출방법(기본), Qiskit Version Up으로 제작성 및 최적화
# 작성자: 박문기(mkbahk@gmail.com)
# 최초작성일: 20230926
# 마지막수정일: 20240308
# 수정사유: Qiskit 1.0.2 Update 반영
######################################################

In [2]:
!python3 -m pip install qiskit[visualization]
!python3 -m pip install qiskit-ionq
!python3 -m pip install qiskit-ibm-provider
!python3 -m pip install qiskit-aer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 39.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 68.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.4/39.4 MB 17.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 16.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.5/107.5 kB 12.3 MB/s eta 0:00:00
  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136816 sha256=0ccc657a157d642d4844fd8cdcd71364e6a6a142b351cdfab37f8adbcb3b7bd4
  Stored in directory: /root/.cache/pip/wheels/d3/31/8b/e09b0386afd80cfc556c00408c9aeea5c35c4d484a9c762fd5
Successfully built pylatexenc
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 6.1 MB/s eta 0:00:00
  Attempting unin

In [17]:
#Conjugated with Real Number
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A_C = np.conj(A)

print(A_C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#Conjugated with Complex Number

import numpy as np

A = np.array([[-1+2j, -3-4j, 5+6j],
              [7-8j, 9+10j, 11-12j],
              [13+14j, 15-16j, 17+18j]])

A_C = np.conj(A)

print(A_C)

[[-1. -2.j -3. +4.j  5. -6.j]
 [ 7. +8.j  9.-10.j 11.+12.j]
 [13.-14.j 15.+16.j 17.-18.j]]


In [22]:
#Transpose

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A_T = A.transpose()

print(A_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
#Conjugated Transpose with Complex Number

import numpy as np

A = np.array([[1+2j, 3-4j, 5+6j],
              [7-8j, 9+10j, 11-12j],
              [13+14j, 15-16j, 17+18j]])

A_H = np.conj(A.transpose())

print(A_H)

[[ 1. -2.j  7. +8.j 13.-14.j]
 [ 3. +4.j  9.-10.j 15.+16.j]
 [ 5. -6.j 11.+12.j 17.-18.j]]


In [ ]:
import qiskit.utils
qiskit.utils.local_hardware_info()

{'python_compiler': 'GCC 11.4.0',
 'python_build': 'main, Nov 20 2023 15:14:05',
 'python_version': '3.10.12',
 'os': 'Linux',
 'cpus': 1}