<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/LinearAgebraByNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#단위형렬

A = np.array([[1, 0], [0,1]])
print(A)

[[1 0]
 [0 1]]


In [3]:
#정규행렬
A = np.array([[1, 2], [2, 3]])
print(np.linalg.norm(A))
print(np.linalg.norm(A.T))

4.242640687119285
4.242640687119285


In [4]:
print(A @ A.T)

[[ 5  8]
 [ 8 13]]


In [6]:
# 양의 정부호 행렬
A = np.array([[1, 2], [2, 3]])
print(np.linalg.eigvals(A))

[-0.23606798  4.23606798]


In [8]:
#행렬곱 외적, 내적, 텐서곱 수행함수 정의

def outer(a, b):
  """행렬외적을 계산합니다."""
  assert len(a.shape) == 1
  assert len(b.shape) == 1
  return np.stack([a * b] * len(b), axis=0)
###def

def dot(a, b):
  """행렬내적을 계산합니다."""
  assert a.shape[1] == b.shape[0]
  return np.sum(a * b, axis=1)
###def

def tensordot(a, b, axes):
  """텐서곱을 계산합니다."""
  return np.einsum(a.shape + b.shape, axes)
###def

In [9]:
# 행렬외적의 예
a = np.array([1, 2])
b = np.array([3, 4])
c = outer(a, b)
print(c)

[[3 8]
 [3 8]]


In [10]:
# 행렬내적의 예
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = dot(a, b)
print(c)

[17 53]


In [12]:
# 텐서곱의 예
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
d = tensordot(a, b, axes=(2, 0))
print(d)

ValueError: ignored