<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/MatrixInnerProduct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 행렬내적을 계산합니다.
dot = np.dot(a, b)

# 출력
print(dot)

[[19 22]
 [43 50]]


In [6]:
M1 = np.array([
    [1, 1],
    [0, 0]])
M2 = np.array([
    [0, 1],
    [1, 0]])

# 행렬내적을 계산합니다.
dot = np.dot(M1, M2)
# 출력
print("M1M2=\n", dot)

#행렬내적의 교환법칙이 성립되지 않음을 확인
dot = np.dot(M2, M1)
# 출력
print("M2M1=\n",dot)

M1M2=
 [[1 1]
 [0 0]]
M2M1=
 [[0 0]
 [1 1]]
