<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/MatrixManuplationWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
A = np.identity(n=3, dtype=float)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A = np.identity(n=3, dtype=complex)
A

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [10]:
A = np.array(
    [[1, 2],
    [3, 4]])
A.T

array([[1, 3],
       [2, 4]])

In [11]:
A = np.array(
    [[1+1j, 2+1j],
    [3-1j, 4-1j]])
A.T

array([[1.+1.j, 3.-1.j],
       [2.+1.j, 4.-1.j]])

In [14]:
A = np.array(
    [[1, 2],
     [3, 4]])

np.linalg.det(A)

-2.0000000000000004

In [15]:
A = np.array(
    [[1, 2],
     [3, 4]])
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [17]:
A = np.array(
    [[1+1j, 2+1j],
     [3-1j, 4-1j]])
A_inv = np.linalg.inv(A)
A_inv

array([[-1.25000000e+00-0.75j,  2.50000000e-01+0.75j],
       [ 1.00000000e+00+0.5j , -8.32667268e-17-0.5j ]])

In [18]:
A @ A_inv

array([[1.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j],
       [1.11022302e-16+4.44089210e-16j, 1.00000000e+00-2.22044605e-16j]])

In [23]:
def unitary_matrix(n):
  """
  n차원 unitary matrix를 생성합니다.

  Args:
    n: 행렬의 차원

  Returns:
    n차원 unitary matrix
  """

  # n개의 복소수 단위벡터를 생성합니다.
  unit_vectors = np.random.randn(n, n) + 1j * np.random.randn(n, n)

  # 행렬의 각 행의 내적을 1로 맞춥니다.
  for i in range(n):
    unit_vectors[i] = unit_vectors[i] / np.linalg.norm(unit_vectors[i])
  ###for

  return unit_vectors
###def

In [24]:
# 사용 예제
#A = unitary_matrix(3)
A = unitary_matrix(n = 3)
print(A)

[[ 0.04558988-0.12230214j  0.28173864-0.86029452j  0.05850563-0.40007188j]
 [ 0.68619794-0.22994688j  0.10719688+0.56150234j  0.33830088-0.18717179j]
 [ 0.07310326+0.15059647j -0.49898295-0.17542233j -0.83108795-0.03889046j]]
