<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/MatrixCalcwithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np

In [57]:
#Euclidean norm

# 양자 상태를 생성합니다.
v = np.array(
    [1, 2, 3]
    )

# Euclidean norm을 계산합니다.
norm = np.linalg.norm(v, ord=2)

# 출력
print(norm)

3.7416573867739413


In [58]:
a = np.array(
    [[1, 2],
    [3, 4]]
    )
b = np.array(
    [[5, 6],
     [7, 8]]
    )

# 행렬내적을 계산합니다.
dot = np.dot(a, b)

# 출력
print(dot)

[[19 22]
 [43 50]]


In [78]:
M1 = np.array(
    [[1, 1],
    [0, 0]]
    )
M2 = np.array(
    [[0, 1],
    [1, 0]]
    )

# 행렬내적을 계산합니다.
dot = np.dot(M1, M2)
# 출력
print("M1M2=\n", dot)

#행렬내적의 교환법칙이 성립되지 않음을 확인
dot = np.dot(M2, M1)
# 출력
print("M2M1=\n",dot)

M1M2=
 [[1 1]
 [0 0]]
M2M1=
 [[0 0]
 [1 1]]


In [80]:
#텐서곱 예

M1 = np.array(
    [[1, 2],
    [3, 4]]
    )
M2 = np.array(
    [[1, 2],
    [3, 4]]
    )

# 텐서곱을 계산합니다.
dot = np.kron(M1, M2)
print(dot)

[[ 1  2  2  4]
 [ 3  4  6  8]
 [ 3  6  4  8]
 [ 9 12 12 16]]


In [77]:
# 두 개의 행렬을 생성합니다.
matrix_H = np.array(
    [[1/np.sqrt(2), 1/np.sqrt(2)],
     [1/np.sqrt(2), -(1/np.sqrt(2))]]
    )

matrix_S = np.array(
    [[1, 0],
     [0, 1.0j]]
    )

# 두 행렬의 텐서 곱 계산
dot_product = np.dot(matrix_H, np.dot(matrix_S, matrix_H))

# 결과 출력
print("두 행렬의 내적 곱:")
print(dot_product)
print("\n결과에 대한 제곱:")
print(np.square(dot_product))
print("\n결과에 대한 제곱:")
print(np.square([[(1+1.0j)/2, (1-1.0j)/2],[(1-1.0j)/2, (1+1.0j)/2]]))

두 행렬의 내적 곱:
[[0.5+0.5j 0.5-0.5j]
 [0.5-0.5j 0.5+0.5j]]

결과에 대한 제곱:
[[0.+0.5j 0.-0.5j]
 [0.-0.5j 0.+0.5j]]

결과에 대한 제곱:
[[0.+0.5j 0.-0.5j]
 [0.-0.5j 0.+0.5j]]


In [61]:
# 행렬을 생성합니다.
# Python에서는 허수를 나타낼 때 i가 아니고 j로 나타냅니다.
a = np.array(
    [[1, 1+2j],
    [3, 4-1j]]
    )

#conjugate
print("Conjugated =")
print(np.conj(a))

# conjugate transpose를 구합니다.
print("Conjugated Transpose =")
print(np.conj(a).T)


Conjugated =
[[1.-0.j 1.-2.j]
 [3.-0.j 4.+1.j]]
Conjugated Transpose =
[[1.-0.j 3.-0.j]
 [1.-2.j 4.+1.j]]
