<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/MatrixCalcwithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
#Euclidean norm

# 양자 상태를 생성합니다.
v = np.array([1, 2, 3])

# Euclidean norm을 계산합니다.
norm = np.linalg.norm(v, ord=2)

# 출력
print(norm)

3.7416573867739413


In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 행렬내적을 계산합니다.
dot = np.dot(a, b)

# 출력
print(dot)

[[19 22]
 [43 50]]


In [12]:
M1 = np.array([
    [1, 1],
    [0, 0]])
M2 = np.array([
    [0, 1],
    [1, 0]])

# 행렬내적을 계산합니다.
dot = np.dot(M1, M2)
# 출력
print("M1M2=\n", dot)

#행렬내적의 교환법칙이 성립되지 않음을 확인
dot = np.dot(M2, M1)
# 출력
print("M2M1=\n",dot)

M1M2=
 [[1 1]
 [0 0]]
M2M1=
 [[0 0]
 [1 1]]


In [13]:
# 두 개의 행렬을 생성합니다.
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

# 두 행렬의 텐서 곱 계산
tensor_product = np.kron(matrix_A, matrix_B)

# 결과 출력
print("두 행렬의 텐서 곱:")
print(tensor_product)

두 행렬의 텐서 곱:
[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


In [18]:
# 행렬을 생성합니다.
a = np.array([[1, 1+2j], [3, 4-1j]])

#conjugate
print("Conjugated =")
print(np.conj(a))

# conjugate transpose를 구합니다.
print("Conjugated Transpose =")
print(np.conj(a).T)


Conjugated =
[[1.-0.j 1.-2.j]
 [3.-0.j 4.+1.j]]
Conjugated Transpose =
[[1.-0.j 3.-0.j]
 [1.-2.j 4.+1.j]]
