<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/QuantumInnerOuterTensorProduct_mkbahk_20250822.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 벡터 정의
V = np.array([-6, 9j])
W = np.array([3, -8])

# V의 켤레 전치 (conjugate transpose)
V_conj = np.conjugate(V)

# 내적 계산
result = np.dot(V_conj, W)

print("V의 켤레 전치와 W의 내적 결과:", result)

V의 켤레 전치와 W의 내적 결과: (-18+72j)


In [3]:
import numpy as np

# 벡터 정의
V = np.array([-3j, 9])
W = np.array([9j, 2])

# W의 켤레 전치 (conjugate transpose)
W_conj = np.conjugate(W)

# 외적 계산
result = np.outer(V, W_conj)

print("V와 W의 켤레 전치의 외적 결과:\n", result)

V와 W의 켤레 전치의 외적 결과:
 [[-27. +0.j  -0. -6.j]
 [  0.-81.j  18. +0.j]]


In [4]:
import numpy as np

# 행렬 정의
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 텐서 곱 계산
result = np.kron(A, B)

print("텐서 곱 결과:\n", result)

텐서 곱 결과:
 [[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
