<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/x_gate%EC%99%80_cnot_gate%EC%9D%98_%ED%96%89%EB%A0%AC%EC%97%B0%EC%82%B0%EC%A6%9D%EB%AA%85_20240326.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
######################################################
# 코드의 목적: X-Gate와 CNOT-gate로 연결된 2 큐빗을 행렬연산으로 증명
# 작성자: 박문기(mkbahk@gmail.com)
# 최초작성일: 20240326
# 마지막수정일: 20240326
######################################################

In [1]:
!python3 -m pip install qiskit[visualization]
!python3 -m pip install qiskit-ionq
!python3 -m pip install qiskit-ibm-provider
!python3 -m pip install qiskit-aer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 49.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 68.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.4/39.4 MB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 18.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.5/107.5 kB 13.0 MB/s eta 0:00:00
  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136816 sha256=d724e3088ee227bb0cb8c929099bf27308ecfda0db0d44de0f56aa2829f7533d
  Stored in directory: /root/.cache/pip/wheels/d3/31/8b/e09b0386afd80cfc556c00408c9aeea5c35c4d484a9c762fd5
Successfully built pylatexenc
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 7.5 MB/s eta 0:00:00
  Attempting uni

In [11]:
import numpy as np

# 2행 1열 행렬 정의
a = np.array([[1],
              [0]])

# 2행 2열 행렬 정의
b = np.array([[0, 1],
              [1, 0]])

# 내적 계산
inner_product = np.dot(a.T, b)

# 결과 출력
print(inner_product)


[[0 1]]


In [29]:
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_q = QuantumRegister(2, 'q')
creg_c = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

circuit.x(qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.measure(qreg_q[0], creg_c[0])
circuit.measure(qreg_q[1], creg_c[1])
circuit.draw()

┌───┐     ┌─┐   
q_0: ┤ X ├──■──┤M├───
     └───┘┌─┴─┐└╥┘┌─┐
q_1: ─────┤ X ├─╫─┤M├
          └───┘ ║ └╥┘
c: 2/═══════════╩══╩═
                0  1

In [31]:
import numpy as np
# 두 행렬 생성
zero_vector = np.array([[1], [0]])
#one_vector = np.array([[0], [1]])
x_gate = np.array([[0, 1],
                   [1, 0]])
#
cnot_gate = np.array([[1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [0, 0, 1, 0],
                      [0, 1, 0, 0]])
#
result=np.dot(x_gate, zero_vector)
print(result)
#
tensor_product = np.kron(zero_vector, result)
print(tensor_product)
#
new_result = np.dot(cnot_gate, tensor_product)
print(new_result)

[[0]
 [1]]
[[0]
 [1]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [1]]
