<a href="https://colab.research.google.com/github/mkbahk/QuantumComputing/blob/main/x_gate%EC%99%80_cnot_gate%EC%9D%98_%ED%96%89%EB%A0%AC%EC%97%B0%EC%82%B0%EC%A6%9D%EB%AA%85_20240326.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
##########################################################
# 코드의 목적: X-Gate와 CNOT-gate로 연결된 2 큐빗을 행렬연산으로 증명
# 작성자: 박문기(mkbahk@gmail.com)
# 최초작성일: 20240326
# 마지막수정일: 20240326
##########################################################

In [33]:
!python3 -m pip install qiskit[visualization]
!python3 -m pip install qiskit-ionq
!python3 -m pip install qiskit-ibm-provider
!python3 -m pip install qiskit-aer

In [34]:
import numpy as np

# 2행 1열 행렬 정의
a = np.array([[1],
              [0]])

# 2행 2열 행렬 정의
b = np.array([[0, 1],
              [1, 0]])

# 내적 계산
inner_product = np.dot(a.T, b)

# 결과 출력
print(inner_product)


[[0 1]]


In [35]:
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_q = QuantumRegister(2, 'q')
creg_c = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

circuit.x(qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.measure(qreg_q[0], creg_c[0])
circuit.measure(qreg_q[1], creg_c[1])
circuit.draw()

┌───┐     ┌─┐   
q_0: ┤ X ├──■──┤M├───
     └───┘┌─┴─┐└╥┘┌─┐
q_1: ─────┤ X ├─╫─┤M├
          └───┘ ║ └╥┘
c: 2/═══════════╩══╩═
                0  1

In [31]:
import numpy as np
# 두 행렬 생성
zero_vector = np.array([[1], [0]])
#one_vector = np.array([[0], [1]])
x_gate = np.array([[0, 1],
                   [1, 0]])
#
cnot_gate = np.array([[1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [0, 0, 1, 0],
                      [0, 1, 0, 0]])
#
result=np.dot(x_gate, zero_vector)
print(result)
#
tensor_product = np.kron(zero_vector, result)
print(tensor_product)
#
new_result = np.dot(cnot_gate, tensor_product)
print(new_result)

[[0]
 [1]]
[[0]
 [1]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [1]]
